package com.artist.scrapper;

import org.jsoup.Connection;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.parser.Parser;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.Date;

public class TSScrapperUtils
{
    public static Document getJSoupHtmlDocument(final String url)
    {
        Document result = null;

        try
        {
            Connection dom = Jsoup.connect(url);
            result = dom.get();

        }
        catch (IOException ioe)
        {
            System.err.println(ioe.getMessage());
        }
        return result;
    }


    public static Document getJSoupXmlDocument(final String url)
    {
        final String rawXml = getTextFromURL(url);

        return Jsoup.parse(rawXml, "", Parser.xmlParser());
    }



    public static Integer getDifferenceInSeconds(final Date firstDate, final Date secondDate)
    {
        Integer result = null;

        final Long secondsLeft = (secondDate.getTime() - firstDate.getTime()) / 1000;

        if ((secondsLeft > 0) &&
                (secondsLeft < Integer.MAX_VALUE))
        {
            result = secondsLeft.intValue();
        }

        return result;
    }



    public static String getTextFromURL(final String url)
    {
        StringBuilder result = new StringBuilder();
        try
        {
            final URL website = new URL(url);
            final URLConnection connection = website.openConnection();
            final BufferedReader in = new BufferedReader(
                    new InputStreamReader(
                            connection.getInputStream()));

            String inputLine;

            while ((inputLine = in.readLine()) != null)
                result.append(inputLine);

            in.close();

        }
        catch (MalformedURLException e)
        {
            e.printStackTrace();  //TODO FCRES: Autogenerated, modify
        }
        catch (IOException e)
        {
            e.printStackTrace();  //TODO FCRES: Autogenerated, modify
        }


        return result.toString();
    }

}
